In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\user\Desktop\Python Files\shopping_behavior_updated.csv', sep=',', encoding='utf-8')
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(r'[^\w]+', '_', regex=True)
)
df = df.set_index('customer_id')
df

,age,gender,item_purchased,category,purchase_amount_usd_,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
customer_id,,,,,,,,,,,,,,,,
1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly
2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly
3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly
4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly
5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly
3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Fortnightly
3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly
3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly
3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly

In [3]:
df = df.rename(columns={'purchase_amount_usd_': 'purchase_amount_usd'})

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3900 entries, 1 to 3900
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     3900 non-null   int64
 1   gender                  3900 non-null   object
 2   item_purchased          3900 non-null   object
 3   category                3900 non-null   object
 4   purchase_amount_usd     3900 non-null   int64
 5   location                3900 non-null   object
 6   size                    3900 non-null   object
 7   color                   3900 non-null   object
 8   season                  3900 non-null   object
 9   review_rating           3900 non-null   float64
 10  subscription_status     3900 non-null   object
 11  shipping_type           3900 non-null   object
 12  discount_applied        3900 non-null   object
 13  previous_purchases      3900 non-null   int64
 14  payment_method          3900 non-null   object
 15  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(3), object(12)
memory usage: 518.0+ KB

In [6]:
(df['discount_applied'] == df['promo_code_used']).all()

In [8]:
df['frequency_of_purchases'] = df['frequency_of_purchases'].replace('Every 3 Months', 'Quarterly')
df['frequency_of_purchases'] = df['frequency_of_purchases'].replace('Bi-Weekly', 'Fortnightly')
df = df.drop('promo_code_used', axis=1)
df

,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
customer_id,,,,,,,,,,,,,,,,
1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly
2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly
3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly
4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly
5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly
3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Fortnightly
3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly
3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly
3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly

In [9]:
df.to_csv(r'C:\Users\user\Desktop\Python Files\shopping_behavior_updated.csv')

In [10]:
from scipy import stats

In [11]:
group_a = df[df['gender'] == 'Male']['purchase_amount_usd']
group_b = df[df['gender'] == 'Female']['purchase_amount_usd']

t_stat, p_value = stats.ttest_ind(group_a, group_b)

print('t-statistic: ', t_stat)
print('p-value: ', p_value)

t-statistic:  -0.8769152065030424
p-value:  0.38058673555268097

In [12]:
group_a = df[df['gender'] == 'Male']['previous_purchases']
group_b = df[df['gender'] == 'Female']['previous_purchases']

t_stat, p_value = stats.ttest_ind(group_a, group_b)

print('t-statistic: ', t_stat)
print('p-value: ', p_value)

t-statistic:  2.2411114300556023
p-value:  0.025074934371703963

In [13]:
# creating age grous
df['age_group'] = (df['age'] // 10) * 10
df['age_group'] = df['age_group'].astype(str) + '-' + (df['age_group'] + 10).astype(str)

group1 = df[df['age_group'] == '10-20']['purchase_amount_usd']
group2 = df[df['age_group'] == '20-30']['purchase_amount_usd']
group3 = df[df['age_group'] == '30-40']['purchase_amount_usd']
group4 = df[df['age_group'] == '40-50']['purchase_amount_usd']
group5 = df[df['age_group'] == '50-60']['purchase_amount_usd']
group6 = df[df['age_group'] == '60-70']['purchase_amount_usd']
group7 = df[df['age_group'] == '70-80']['purchase_amount_usd']

anova = stats.f_oneway(group1, group2, group3, group4, group5, group6, group7)  # ANOVA
kruskal = stats.kruskal(group1, group2, group3, group4, group5, group6, group7)
print(anova)
print(kruskal)

F_onewayResult(statistic=np.float64(0.6941389530573652), pvalue=np.float64(0.6543928936577698))
KruskalResult(statistic=np.float64(4.131971255014301), pvalue=np.float64(0.6588224226220389))

In [14]:
# ANOVA WELCH
import pingouin as pg

pg.welch_anova(dv='purchase_amount_usd', between='age_group', data=df)

      Source  ddof1       ddof2         F     p-unc       np2
0  age_group      6  632.387065  0.695516  0.653343  0.001069

In [15]:
print(stats.shapiro(group1))  # тест на нормальность
print(stats.levene(group1, group2, group3, group4, group5, group6, group7))  # тест на одинаковость дисперсий

ShapiroResult(statistic=np.float64(0.9554596083793144), pvalue=np.float64(9.57536420470474e-05))
LeveneResult(statistic=np.float64(0.6446093640185095), pvalue=np.float64(0.694571702850263))

In [16]:
# age_group vs previous_purchases

pg.welch_anova(dv='previous_purchases', between='age_group', data=df)

      Source  ddof1       ddof2         F     p-unc       np2
0  age_group      6  633.650228  1.970106  0.067818  0.002943

In [17]:
group_a = df[df['subscription_status'] == 'Yes']['purchase_amount_usd']
group_b = df[df['subscription_status'] == 'No']['purchase_amount_usd']

t_stat, p_value = stats.ttest_ind(group_a, group_b)

print('t-statistic: ', t_stat)
print('p-value: ', p_value)

t-statistic:  -0.4368012420060051
p-value:  0.6622796924526246

In [18]:
group_a = df[df['subscription_status'] == 'Yes']['previous_purchases']
group_b = df[df['subscription_status'] == 'No']['previous_purchases']

t_stat, p_value = stats.ttest_ind(group_a, group_b)

print('t-statistic: ', t_stat)
print('p-value: ', p_value)

t-statistic:  1.9275950061209202
p-value:  0.053978096177601985

In [19]:
print(pg.welch_anova(dv='purchase_amount_usd', between='frequency_of_purchases', data=df))
print(pg.welch_anova(dv='previous_purchases', between='frequency_of_purchases', data=df))

                   Source  ddof1        ddof2        F     p-unc      np2
0  frequency_of_purchases      4  1637.009399  0.28729  0.886348  0.00029
                   Source  ddof1        ddof2         F     p-unc       np2
0  frequency_of_purchases      4  1640.015805  1.082155  0.363736  0.001108

In [20]:
# discount and purchase amount

group_a = df[df['discount_applied'] == 'Yes']['purchase_amount_usd']
group_b = df[df['discount_applied'] == 'No']['purchase_amount_usd']

t_stat, p_value = stats.ttest_ind(group_a, group_b)

print(t_stat, p_value)

-1.1113791657829266 0.2664737200577539

In [21]:
# new, returning and loyal customers
pg.welch_anova(dv='purchase_amount_usd', between='previous_purchases', data=df)

               Source  ddof1        ddof2         F     p-unc       np2
0  previous_purchases     49  1315.862845  1.078571  0.331721  0.014001

In [22]:
df['discount_status'] = (df['discount_applied'] == 'Yes').astype(int)
pg.welch_anova(dv='discount_status', between='previous_purchases', data=df)

               Source  ddof1        ddof2         F     p-unc       np2
0  previous_purchases     49  1315.871872  1.119318  0.267467  0.013755